import { Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({src: '../font/InriaSerif-Regular.ttf'})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-white dark:bg-black">
        <main className={myFont.className}>{children}</main>
      </body>
    </html>
  );
}
