import { Inter } from "next/font/google";
import localFont from "next/font/local"
import { UserProvider } from '@auth0/nextjs-auth0/client';
import "./globals.css";
import Heading from "~/layout/heading";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: '../font/InriaSerif-Regular.ttf' })

export const metadata = {
  title: "My Profile",
  description: "Generated by My Profile",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="h-full">
      <UserProvider>
        <body className="h-full bg-white dark:bg-gray-800">
          <Heading />
          <main className={myFont.className}>{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
